[pytest]

addopts =
    --strict-markers

markers =
    positive: for positive tests
    negative: for negative tests
    triangle: to check triangle functionality
    regression: to run regression tests
    smoke: to run smoke tests
    prime: to check prime functionality
    qaauto_api: api tests for qa_auto endpoints
    swapi: api tests for swapi endpoints
    ui: for ui saucedemo tests
; python_files = *_automation.py
; python_functions = tc_*